import 'package:flutter/material.dart';

/// Represents different recurrence patterns for reminders
enum RecurrenceType {
  NONE,       // One-time reminder
  DAILY,      // Daily recurrence
  WEEKLY,     // Weekly recurrence
  MONTHLY,    // Monthly recurrence
  QUARTERLY,  // Quarterly recurrence
  YEARLY,     // Yearly recurrence
  CUSTOM,     // Custom interval
}

/// Reminder priority levels
enum ReminderPriority {
  LOW,
  MEDIUM,
  HIGH,
  URGENT,
}

/// Reminder model for calendar integration
class ReminderModel {
  final int? id;
  final String title;
  final String description;
  final DateTime reminderDate;
  final RecurrenceType recurrenceType;
  final int? recurrenceInterval; // Custom interval in days
  final ReminderPriority priority;
  final bool isEnabled;
  final bool isAutoGenerated; // True if generated from invoice/tax patterns
  final String? relatedItemId;
  final String? relatedItemType; // 'invoice', 'tax', 'document'
  final Map<String, dynamic>? metadata;
  final DateTime? nextOccurrence;
  final DateTime? lastTriggered;
  final DateTime createdAt;
  final DateTime updatedAt;

  ReminderModel({
    this.id,
    required this.title,
    required this.description,
    required this.reminderDate,
    this.recurrenceType = RecurrenceType.NONE,
    this.recurrenceInterval,
    this.priority = ReminderPriority.MEDIUM,
    this.isEnabled = true,
    this.isAutoGenerated = false,
    this.relatedItemId,
    this.relatedItemType,
    this.metadata,
    this.nextOccurrence,
    this.lastTriggered,
    required this.createdAt,
    required this.updatedAt,
  });

  // Color coding for priority levels
  Color get priorityColor {
    switch (priority) {
      case ReminderPriority.LOW:
        return Colors.green.shade600;
      case ReminderPriority.MEDIUM:
        return Colors.blue.shade600;
      case ReminderPriority.HIGH:
        return Colors.orange.shade600;
      case ReminderPriority.URGENT:
        return Colors.red.shade600;
    }
  }

  // Icon for reminder type
  IconData get reminderIcon {
    if (isAutoGenerated) {
      switch (relatedItemType) {
        case 'invoice':
          return Icons.receipt_long_rounded;
        case 'tax':
          return Icons.account_balance_rounded;
        case 'document':
          return Icons.description_rounded;
        default:
          return Icons.smart_toy_rounded;
      }
    }

    switch (recurrenceType) {
      case RecurrenceType.NONE:
        return Icons.notification_add_rounded;
      case RecurrenceType.DAILY:
        return Icons.today_rounded;
      case RecurrenceType.WEEKLY:
        return Icons.view_week_rounded;
      case RecurrenceType.MONTHLY:
        return Icons.calendar_month_rounded;
      case RecurrenceType.QUARTERLY:
        return Icons.calendar_view_month_rounded;
      case RecurrenceType.YEARLY:
        return Icons.event_rounded;
      case RecurrenceType.CUSTOM:
        return Icons.repeat_rounded;
    }
  }

  // Human readable priority name
  String get priorityDisplayName {
    switch (priority) {
      case ReminderPriority.LOW:
        return 'Düşük';
      case ReminderPriority.MEDIUM:
        return 'Orta';
      case ReminderPriority.HIGH:
        return 'Yüksek';
      case ReminderPriority.URGENT:
        return 'Acil';
    }
  }

  // Human readable recurrence type name
  String get recurrenceDisplayName {
    switch (recurrenceType) {
      case RecurrenceType.NONE:
        return 'Tek seferlik';
      case RecurrenceType.DAILY:
        return 'Günlük';
      case RecurrenceType.WEEKLY:
        return 'Haftalık';
      case RecurrenceType.MONTHLY:
        return 'Aylık';
      case RecurrenceType.QUARTERLY:
        return 'Üç aylık';
      case RecurrenceType.YEARLY:
        return 'Yıllık';
      case RecurrenceType.CUSTOM:
        return 'Özel (${recurrenceInterval ?? 0} gün)';
    }
  }

  // Calculate next occurrence based on recurrence type
  DateTime? calculateNextOccurrence() {
    if (recurrenceType == RecurrenceType.NONE) return null;

    final base = lastTriggered ?? reminderDate;
    
    switch (recurrenceType) {
      case RecurrenceType.DAILY:
        return base.add(const Duration(days: 1));
      case RecurrenceType.WEEKLY:
        return base.add(const Duration(days: 7));
      case RecurrenceType.MONTHLY:
        return DateTime(base.year, base.month + 1, base.day);
      case RecurrenceType.QUARTERLY:
        return DateTime(base.year, base.month + 3, base.day);
      case RecurrenceType.YEARLY:
        return DateTime(base.year + 1, base.month, base.day);
      case RecurrenceType.CUSTOM:
        return base.add(Duration(days: recurrenceInterval ?? 30));
      case RecurrenceType.NONE:
        return null;
    }
  }

  // Check if reminder is due today
  bool get isDueToday {
    final today = DateTime.now();
    final dueDate = nextOccurrence ?? reminderDate;
    return dueDate.year == today.year &&
           dueDate.month == today.month &&
           dueDate.day == today.day;
  }

  // Check if reminder is overdue
  bool get isOverdue {
    final today = DateTime.now();
    final dueDate = nextOccurrence ?? reminderDate;
    return dueDate.isBefore(today) && !isDueToday;
  }

  // Create ReminderModel from database map
  factory ReminderModel.fromMap(Map<String, dynamic> map) {
    return ReminderModel(
      id: map['id'] as int?,
      title: map['title'] as String,
      description: map['description'] as String,
      reminderDate: DateTime.parse(map['reminder_date'] as String),
      recurrenceType: RecurrenceType.values[map['recurrence_type'] as int],
      recurrenceInterval: map['recurrence_interval'] as int?,
      priority: ReminderPriority.values[map['priority'] as int],
      isEnabled: (map['is_enabled'] as int) == 1,
      isAutoGenerated: (map['is_auto_generated'] as int) == 1,
      relatedItemId: map['related_item_id'] as String?,
      relatedItemType: map['related_item_type'] as String?,
      metadata: map['metadata'] != null 
          ? Map<String, dynamic>.from(map['metadata'] as Map)
          : null,
      nextOccurrence: map['next_occurrence'] != null 
          ? DateTime.parse(map['next_occurrence'] as String)
          : null,
      lastTriggered: map['last_triggered'] != null 
          ? DateTime.parse(map['last_triggered'] as String)
          : null,
      createdAt: DateTime.parse(map['created_at'] as String),
      updatedAt: DateTime.parse(map['updated_at'] as String),
    );
  }

  // Convert ReminderModel to database map
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'reminder_date': reminderDate.toIso8601String(),
      'recurrence_type': recurrenceType.index,
      'recurrence_interval': recurrenceInterval,
      'priority': priority.index,
      'is_enabled': isEnabled ? 1 : 0,
      'is_auto_generated': isAutoGenerated ? 1 : 0,
      'related_item_id': relatedItemId,
      'related_item_type': relatedItemType,
      'metadata': metadata,
      'next_occurrence': nextOccurrence?.toIso8601String(),
      'last_triggered': lastTriggered?.toIso8601String(),
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  // Copy with method for updates
  ReminderModel copyWith({
    int? id,
    String? title,
    String? description,
    DateTime? reminderDate,
    RecurrenceType? recurrenceType,
    int? recurrenceInterval,
    ReminderPriority? priority,
    bool? isEnabled,
    bool? isAutoGenerated,
    String? relatedItemId,
    String? relatedItemType,
    Map<String, dynamic>? metadata,
    DateTime? nextOccurrence,
    DateTime? lastTriggered,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return ReminderModel(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      reminderDate: reminderDate ?? this.reminderDate,
      recurrenceType: recurrenceType ?? this.recurrenceType,
      recurrenceInterval: recurrenceInterval ?? this.recurrenceInterval,
      priority: priority ?? this.priority,
      isEnabled: isEnabled ?? this.isEnabled,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      relatedItemId: relatedItemId ?? this.relatedItemId,
      relatedItemType: relatedItemType ?? this.relatedItemType,
      metadata: metadata ?? this.metadata,
      nextOccurrence: nextOccurrence ?? this.nextOccurrence,
      lastTriggered: lastTriggered ?? this.lastTriggered,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() {
    return 'ReminderModel(id: $id, title: $title, reminderDate: $reminderDate, recurrenceType: $recurrenceType)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is ReminderModel &&
        other.id == id &&
        other.title == title &&
        other.reminderDate == reminderDate &&
        other.recurrenceType == recurrenceType;
  }

  @override
  int get hashCode {
    return id.hashCode ^
        title.hashCode ^
        reminderDate.hashCode ^
        recurrenceType.hashCode;
  }
} 